site_name: Fundamentals
site_url: https://pages.github.ibm.com/watson-foundation-services/icp-content-demos/
site_description: daily practice questions on algorithm and system design quesitons
theme: 'material'
repo_name: 'fundamentals'
repo_url: 'https://github.com/SailC/fundamentals.git'
extra:
  logo: 'images/avatar.png'
  palette:
    primary: 'Cyan'
markdown_extensions:
  - codehilite
